Add simpler PR without name-based host pointers and netmasks.
chris-wood/draft-ietf-tls-esni pull request #4
Opened 2019-02-15 03:51 UTC by chris-wood

2019-02-23 01:53 UTC, kazuho reviewed
Just my two cents.

2019-02-23 01:53 UTC, kazuho commented on draft-ietf-tls-esni.md
> +Servers operating in Split Mode SHOULD have DNS configured to return
Maybe s/Servers operating in Split Mode/Client-facing servers/?

I suggest this because the text does not look specific to Split Mode, and unless we make the change, we need to add a paragraph that discusses about Shared Mode separately.

2019-02-23 01:53 UTC, kazuho commented on draft-ietf-tls-esni.md
> +            }
I think the idea of sending addresses is fine, but the problem is how huge the ESNI record would become.

Considering that, I think we need to at least have a netmask field for each address.

We could go a bit farther and do somthing like:
```
struct {
    uint8 netmask;
    opaque address[(netmask + 7) / 8];
} TypedAddress;

struct {
    AddressType address_type;
    TypedAddress addresses<1..2^16-1>;
} AddressList;
```

This saves:
* one byte per entry (because `address_type` appears one per list rather than once per address)
* for IPv4 addresses, saves one byte per entry assuming that the netmask is not greater than /24
* for IPv6 addresses, save like 8 bytes per entry assuming that the netmask is like /64

2019-02-23 01:53 UTC, kazuho commented on draft-ietf-tls-esni.md
> +understand must reject the record.
I do not think there's a need to introduce the concept of "mandatory extensions" considering the fact that `address_set` is not using the `extensions` field.

2019-02-24 02:00 UTC, chris-wood commented on draft-ietf-tls-esni.md
> +Servers operating in Split Mode SHOULD have DNS configured to return
This is not new text -- it's copied.

2019-02-24 02:01 UTC, chris-wood commented on draft-ietf-tls-esni.md
> +            }
What value would the netmask serve? If A/AAAA and ESNI mismatch occurs frequently, then a mask is insufficient. If it doesn't occur frequently, then including anything but a full address seems less optimal. I would prefer to keep this simple here.

2019-02-24 02:02 UTC, chris-wood commented on draft-ietf-tls-esni.md
> +understand must reject the record.
This is one way in which folks can write an extension draft specifying the netmask. I do not think that should be done here.

2019-02-24 03:58 UTC, kazuho commented on draft-ietf-tls-esni.md
> +            }
Two values:
* Using netmask is a space efficient way of representing multiple addresses. Organizations running servers at mass-scale often setup multiple servers (serving same set of origins) within a single network address. I think it's important to keep the size of the structure (and hence the DNS record) small.
* Organizations often install new servers within a pre-allocated network address. Having netmask in the ESNI record removes the necessity to update the ESNI record every time a new server is being installed.

2019-02-24 12:19 UTC, kazuho commented on draft-ietf-tls-esni.md
> +Servers operating in Split Mode SHOULD have DNS configured to return
Ah. Thank you for pointing out that. I missed that. Maybe I need to reread the whole draft.

2019-02-26 23:55 UTC, ekr requested changes

2019-02-26 23:55 UTC, ekr commented on draft-ietf-tls-esni.md
> +refers is not in possession of the ESNI keys.) Naively using this record would
For extra credit, try to make this na\"{i}ve

2019-02-26 23:55 UTC, ekr commented on draft-ietf-tls-esni.md
> +result in handshake failure, and possibly require fallback to plaintext SNI.
I don't think we want to say that. The current spec requires hard failure.

2019-02-26 23:55 UTC, ekr commented on draft-ietf-tls-esni.md
> +ESNIKeys records may indicate a specific IP address(es) for the host(s) in possession
You want MAY, right?

2019-02-26 23:55 UTC, ekr commented on draft-ietf-tls-esni.md
> +AAAA response, initiate TLS with ESNI to the provided address(es).
You want a MUST, right?

2019-02-26 23:55 UTC, ekr commented on draft-ietf-tls-esni.md
> +TLS without ESNI to the provided address(es).
Hmm... So you are saying that the extension is mandatory to have? That doesn't seem right. I would assume that if you had ESNI + A/AAAA then you would be good to go. Otherwise, what's the point of the A/AAAA resolution?

2019-02-27 00:14 UTC, chris-wood commented on draft-ietf-tls-esni.md
> +refers is not in possession of the ESNI keys.) Naively using this record would
I'll just drop this sentence entirely.

2019-02-27 00:14 UTC, chris-wood commented on draft-ietf-tls-esni.md
> +result in handshake failure, and possibly require fallback to plaintext SNI.
Dropped!

2019-02-27 00:14 UTC, chris-wood commented on draft-ietf-tls-esni.md
> +ESNIKeys records may indicate a specific IP address(es) for the host(s) in possession
Yep!

2019-02-27 00:16 UTC, chris-wood commented on draft-ietf-tls-esni.md
> +AAAA response, initiate TLS with ESNI to the provided address(es).
Since this is a suggested algorithm, I left out MUST. Perhaps a SHOULD work suffice?

2019-02-27 16:03 UTC, closed without merging